name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonacion de codigo
      uses: actions/checkout@v4
      
    - name: setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '8'
    
    - name: Compilation Maven
      run: mvn package
      
    - name: Ejecutar pruebas y generar informe de cobertura
      run: mvn clean verify

    - name: Crear PDF del informe de cobertura
      run: mvn pdf:pdf

    - name: Crear artefacto de Jacoco
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/
        
      # se agrega el mismo uses pero con distinto  java-version Para compatibilizar con sonarCloud (solo acepta java 17)
    - name: setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Analisis SonarCloud
      run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=albertoverdugo \
          -Dsonar.projectKey=ALBERTOVERDUGO_microservicio-java


    - name: SonarQube Quality Gate Check
      uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
      with:
          scanMetadataReportFile: target/sonar/report-task.txt
